spring:
  application:
    name: file-storage-service

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test-db
    username: test
    password: test@1234

  h2:
    console:
      enabled: true

file:
  upload:
    path: ./uploads